name: Reusable Welcome
on:
  workflow_call:
    inputs:
      welcome-message:
        required: false
        type: string
        default: "Welcome to the Still Systems workshop! 🛠️ Thank you for your contribution."

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Welcome first-time contributor
        uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: ${{ inputs.welcome-message }}
          pr-message: ${{ inputs.welcome-message }}
